//! Domain event bus — thin wrapper over `tokio::sync::broadcast`.
//!
//! Fans domain events (a request completed, a client connected, etc.) out to
//! every interested surface: the TUI, the MCP server, the `tail` task, and
//! anything else that wants to observe live traffic. The store actor is the
//! sole publisher; everyone else is a subscriber.
//!
//! ## Why `broadcast`, not `mpsc`
//!
//! We need N subscribers to receive every event. `mpsc` is single-consumer.
//! `watch` collapses intermediate values (we'd lose events). `broadcast` fans
//! out lossy-to-slow-consumers, which is exactly right:
//!
//! - Publisher is never blocked by a slow subscriber.
//! - A subscriber that falls behind gets `RecvError::Lagged(n)` telling it
//!   how many events it missed. The intended recovery is "ask the store for
//!   current state and resume" — the TUI does exactly that.
//! - Channel capacity is sized for peak burst ÷ slowest-reasonable drain
//!   latency (currently 1024 slots; see ADR-002 §D-2).
//!
//! ## What does not go through the bus
//!
//! - The raw WS frames (they never leave the per-session task).
//! - Store queries (`all`, `get`, `filter`) — those use mpsc + oneshot replies.
//! - Shutdown signals — those use `tokio_util::sync::CancellationToken`.
//!
//! ## ID types
//!
//! `RequestId` and `ClientId` live here rather than in `store/` because
//! every subscriber needs them and we want to avoid `store` ↔ `bus` import
//! cycles. They are thin newtypes over `Uuid`.

use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;
use uuid::Uuid;

/// Identifier for a single logged HTTP exchange. Generated server-side (by
/// the store actor) on receipt of an `api.response` frame — Reactotron's
/// wire protocol has no per-request id of its own (see ADR-003 §F-2).
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RequestId(pub Uuid);

impl RequestId {
    /// Generate a fresh v4 `RequestId`.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Identifier for a connected Reactotron client (one RN app instance).
/// Generated by the WS server on accept (see ADR-003 §F-7 for why we do
/// not trust the client-supplied `clientId` directly for our own bookkeeping).
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ClientId(pub Uuid);

impl ClientId {
    /// Generate a fresh v4 `ClientId`.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for ClientId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ClientId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Domain events published by the store and consumed by every surface.
///
/// `RequestStarted` is reserved for third-party plugins that split
/// `api.request` / `api.response` into separate frames. The official RN
/// networking plugin never produces it (see ADR-003 §F-1). Keeping the
/// variant costs nothing and lets the bus be forward-compatible without
/// a schema bump.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Event {
    /// A request frame arrived before any response. Never produced from
    /// the official RN plugin; kept as forward-compat.
    RequestStarted(RequestId),
    /// A completed HTTP exchange (request + response) landed in the store.
    /// This is the primary event surface for v1.
    ResponseReceived(RequestId),
    /// A Reactotron client completed its `client.intro` handshake.
    ClientConnected(ClientId),
    /// A Reactotron client's WebSocket closed (either side).
    ClientDisconnected(ClientId),
}

/// A shared publisher handle. Cheap to clone — each clone increments an
/// internal `Arc`. Subscribers call `.subscribe()` on the sender to obtain
/// a `broadcast::Receiver<Event>`.
pub type EventBus = broadcast::Sender<Event>;

/// Create a new event bus with the given ring-buffer capacity.
///
/// `capacity` is the number of events the channel retains for late
/// subscribers. When a subscriber falls behind by more than `capacity`
/// events, its next `recv().await` returns `RecvError::Lagged(n)` and it
/// resumes from the newest buffered event. Publisher throughput is never
/// affected by subscriber speed.
///
/// Rustotron uses 1024 slots in production paths — see ADR-002 §D-2 for
/// the reasoning. Tests typically use `4`–`16` to exercise lag behaviour
/// deterministically.
///
/// # Panics
///
/// Panics if `capacity` is `0` — `tokio::sync::broadcast::channel` rejects
/// zero-capacity channels. Call sites should pass a positive literal.
#[must_use]
pub fn new_bus(capacity: usize) -> EventBus {
    let (tx, _rx) = broadcast::channel(capacity);
    tx
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn fanout_reaches_every_subscriber() {
        let bus = new_bus(16);
        let mut a = bus.subscribe();
        let mut b = bus.subscribe();
        let mut c = bus.subscribe();

        let id = RequestId::new();
        bus.send(Event::ResponseReceived(id))
            .expect("no subscribers should have been dropped yet");

        assert_eq!(a.recv().await.unwrap(), Event::ResponseReceived(id));
        assert_eq!(b.recv().await.unwrap(), Event::ResponseReceived(id));
        assert_eq!(c.recv().await.unwrap(), Event::ResponseReceived(id));
    }

    #[tokio::test]
    async fn slow_subscriber_gets_lagged_fast_subscriber_unaffected() {
        use tokio::sync::broadcast::error::TryRecvError;

        let bus = new_bus(4);
        let mut fast = bus.subscribe();
        let mut slow = bus.subscribe();

        // Overflow the ring by 6 events. `fast` drains as we go; `slow` sits.
        for _ in 0..10_usize {
            bus.send(Event::ResponseReceived(RequestId::new())).unwrap();
            let _ = fast.try_recv(); // absorb as publisher emits, so fast never lags
        }

        // Fast should have received exactly the 10 events we sent, no Lagged.
        assert!(matches!(fast.try_recv(), Err(TryRecvError::Empty)));

        // Slow's first attempt should surface a non-zero Lagged count.
        match slow.try_recv() {
            Err(TryRecvError::Lagged(skipped)) => {
                assert!(
                    skipped >= 1,
                    "subscriber should be told how many events it missed"
                );
            }
            other => panic!("expected Lagged, got {other:?}"),
        }

        // After the Lagged hint, slow's cursor has advanced to the oldest
        // retained event. Drain whatever the ring still holds so the next
        // send can be observed cleanly.
        loop {
            match slow.try_recv() {
                Ok(_) => continue,
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Lagged(_)) => continue,
                Err(TryRecvError::Closed) => panic!("channel closed unexpectedly"),
            }
        }

        // Slow is caught up — a fresh event must arrive cleanly.
        bus.send(Event::ClientConnected(ClientId::new())).unwrap();
        match slow.recv().await {
            Ok(Event::ClientConnected(_)) => {}
            other => panic!("slow should resume cleanly after drain; got {other:?}"),
        }
    }

    #[tokio::test]
    async fn sender_clone_is_cheap_and_shares_subscribers() {
        let bus = new_bus(8);
        let bus2 = bus.clone();
        let mut rx = bus.subscribe();

        bus2.send(Event::ClientDisconnected(ClientId::new()))
            .unwrap();

        match rx.recv().await {
            Ok(Event::ClientDisconnected(_)) => {}
            other => panic!("clone should publish to the same channel; got {other:?}"),
        }
    }

    #[tokio::test]
    async fn no_subscribers_send_returns_err_without_panicking() {
        let bus = new_bus(4);
        // No subscribers yet — send should return an error, not panic.
        assert!(bus.send(Event::ClientConnected(ClientId::new())).is_err());
    }

    #[test]
    fn request_id_and_client_id_are_unique() {
        let a = RequestId::new();
        let b = RequestId::new();
        assert_ne!(a, b);
        let c = ClientId::new();
        let d = ClientId::new();
        assert_ne!(c, d);
    }
}
